export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

// export const CREATE_PROJECT_PLAN_REQUEST = 'CREATE_PROJECT_PLAN_REQUEST';
// export const CREATE_PROJECT_PLAN_SUCCESS = 'CREATE_PROJECT_PLAN_SUCCESS';
// export const CREATE_PROJECT_PLAN_FAILURE = 'CREATE_PROJECT_PLAN_FAILURE';
